#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
cd $dir
tmp=/tmp/tmp/$USER/initrd_$$
sh=$(readlink -f $dir/../../admin.sh)

die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
test -n "$1" || die "No out-file"
test -x $sh || die "Not executable [$sh]"
mkdir -p $tmp
$sh install_modules $tmp
cp -R root/* $tmp

cd $tmp
tar cf "$1" *
cd $dir
rm -rf $tmp
