#! /bin/sh
/bin/busybox echo "Uablrek SoC starting..."
/bin/busybox mkdir -p /proc /sys /tmp /dev/pts /dev/shm /var/log \
	/sbin /usr/bin /usr/sbin /dev/mqueue
/bin/busybox rm -rf /etc/mtab /run
/bin/busybox mount -t proc proc /proc
/bin/busybox --install -s
mount -t sysfs sysfs /sys
mdev -s

mkdir -p /run /var/log/dumps /var/tmp
ln -s /run /var/run

#echo /sbin/mdev > /proc/sys/kernel/hotplug
#mount /dev/shm
#mount /dev/pts
#mount -o remount -w /
#mount /dev/mqueue
#mount -t cgroup2 cgroup2 /sys/fs/cgroup

#sysctl -p > /dev/null
test -d /lib/modules && depmod
#ldconfig

exec /sbin/init
